/**
 * exportTest.js — Utilities for exporting and importing test data as formatted TXT files.
 *
 * Functions:
 *  - formatTestAsTxt: Format a single test into a clean, readable text string
 *  - formatAllTestsAsTxt: Format multiple tests into one combined text string
 *  - downloadTxtFile: Trigger a browser download of a .txt file
 *  - parseTxtToTest: Parse an exported test TXT file back into a structured test object
 */

import { uid } from '@/utils/id'

const SEPARATOR = '────────────────────────────────────────'
const SECTION_SEP = '────────────────────────────'

function safeStr(value) {
  return String(value ?? '').trim()
}

function optionLabel(optionId) {
  return String(optionId || '').toUpperCase()
}

function getOptionText(question, optionId) {
  const options = Array.isArray(question?.options) ? question.options : []
  const match = options.find((opt) => String(opt?.id || '').toLowerCase() === String(optionId || '').toLowerCase())
  return match?.text || optionId || '—'
}

function formatDate(dateStr) {
  if (!dateStr) return '—'
  try {
    return new Date(dateStr).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  } catch {
    return String(dateStr)
  }
}

/**
 * Format a single completed test into a clean, readable text string.
 * Includes an encoded structured data block at the bottom for lossless importing.
 *
 * @param {Object} test — Test object with questions, answers, score, etc.
 * @returns {string} — Formatted text representation of the test
 */
export function formatTestAsTxt(test) {
  if (!test) return ''

  const title = safeStr(test.topic || test.title || test.name || 'Untitled Test').toUpperCase()
  const questions = Array.isArray(test.questions) ? test.questions : []
  const answers = test.answers && typeof test.answers === 'object' ? test.answers : {}
  const totalQuestions = questions.length

  // Calculate score from answers if not provided
  let correct = 0
  let wrong = 0
  let skipped = 0

  questions.forEach((q) => {
    const userAnswer = answers[q.id]
    const correctAnswer = String(q.correctAnswer || '').toLowerCase()

    if (!userAnswer) {
      skipped++
    } else if (String(userAnswer).toLowerCase() === correctAnswer) {
      correct++
    } else {
      wrong++
    }
  })

  // Use test's stored score if available, otherwise use calculated
  const scoreCorrect = test.score ?? test.correct ?? correct
  const scoreWrong = test.incorrect ?? wrong
  const scoreSkipped = test.unanswered ?? skipped
  const scorePercentage = test.percentage ?? (totalQuestions > 0 ? Math.round((scoreCorrect / totalQuestions) * 100) : 0)

  const lines = []

  lines.push(SEPARATOR)
  lines.push(title)
  lines.push(SEPARATOR)
  lines.push('')
  lines.push(`Date: ${formatDate(test.completedAt || test.savedAt || test.createdAt)}`)
  lines.push(`Score: ${scoreCorrect} / ${totalQuestions}  (${scorePercentage}%)`)
  lines.push(`Correct: ${scoreCorrect}`)
  lines.push(`Wrong: ${scoreWrong}`)
  lines.push(`Skipped: ${scoreSkipped}`)
  lines.push('')
  lines.push('QUESTIONS')
  lines.push(SEPARATOR)

  questions.forEach((q, index) => {
    const questionNumber = index + 1
    const questionText = safeStr(q.question || q.prompt || q.questionText)
    const options = Array.isArray(q.options) ? q.options : []
    const userAnswer = answers[q.id] || null
    const correctAnswer = String(q.correctAnswer || '').toLowerCase()
    const isCorrect = userAnswer && String(userAnswer).toLowerCase() === correctAnswer
    const isSkipped = !userAnswer

    lines.push('')
    lines.push(`Q${questionNumber}. ${questionText}`)
    lines.push('')

    options.forEach((opt) => {
      lines.push(`  ${optionLabel(opt.id)}. ${safeStr(opt.text)}`)
    })

    lines.push('')

    if (isSkipped) {
      lines.push('Your Answer: (Skipped)')
    } else {
      lines.push(`Your Answer: ${optionLabel(userAnswer)}  —  ${getOptionText(q, userAnswer)}`)
    }

    if (correctAnswer) {
      const resultMark = isSkipped ? '' : isCorrect ? ' ✓' : ' ✗'
      lines.push(`Correct Answer: ${optionLabel(correctAnswer)}  —  ${getOptionText(q, correctAnswer)}${resultMark}`)
    }

    const explanation = safeStr(q.explanation)
    if (explanation) {
      lines.push('')
      lines.push('Explanation:')
      const cleanedExplanation = explanation
        .replace(/\\n/g, '\n')
        .replace(/\\t/g, '  ')
        .split('\n')
        .map((line) => `  ${line.trim()}`)
        .join('\n')
      lines.push(cleanedExplanation)
    }

    lines.push('')
    lines.push(SECTION_SEP)
  })

  lines.push('')
  lines.push(`Generated by LearnLedger`)
  lines.push('')

  // Add structured import token at the bottom of the file
  try {
    const minifiedData = {
      id: test.id || `imported-${Date.now()}-${uid()}`,
      topic: test.topic || test.title || 'Imported Test',
      title: test.title || test.topic || 'Imported Test',
      createdAt: test.createdAt || new Date().toISOString(),
      completedAt: test.completedAt || test.savedAt || new Date().toISOString(),
      questions: test.questions,
      answers: test.answers || {},
      score: scoreCorrect,
      correct: scoreCorrect,
      incorrect: scoreWrong,
      unanswered: scoreSkipped,
      totalQuestions,
      percentage: scorePercentage,
      passed: test.passed ?? (scorePercentage >= 70),
      status: test.status || 'completed'
    }
    const base64Token = btoa(unescape(encodeURIComponent(JSON.stringify(minifiedData))))
    lines.push(`[learnledger-test-data:${base64Token}]`)
  } catch (err) {
    console.warn('Failed to embed JSON metadata in export file:', err)
  }

  return lines.join('\n')
}

/**
 * Format multiple tests into one combined text string.
 */
export function formatAllTestsAsTxt(tests) {
  if (!Array.isArray(tests) || tests.length === 0) return ''

  const header = [
    '═══════════════════════════════════════════════════',
    'LEARNLEDGER — QUESTION BANK EXPORT',
    `Total Tests: ${tests.length}`,
    `Exported: ${formatDate(new Date().toISOString())}`,
    '═══════════════════════════════════════════════════',
    '',
  ].join('\n')

  const formattedTests = tests.map((test, index) => {
    const testHeader = `\n━━━  TEST ${index + 1} of ${tests.length}  ━━━\n`
    return testHeader + formatTestAsTxt(test)
  }).join('\n')

  return header + formattedTests
}

/**
 * Trigger a browser download of a text file.
 */
export function downloadTxtFile(content, filename = 'test-export') {
  const safeName = String(filename || 'test-export')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\-_\s]/g, '')
    .replace(/\s+/g, '-')
    || 'test-export'

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `${safeName}.txt`
  document.body.appendChild(anchor)
  anchor.click()
  document.body.removeChild(anchor)
  URL.revokeObjectURL(url)
}

/**
 * Parse an exported test TXT file back into a structured test object.
 * Supports metadata parsing and full text-based fallback parsing.
 *
 * @param {string} txt — The content of the TXT file
 * @returns {Object} — Reconstructed test object
 */
export function parseTxtToTest(txt) {
  const cleanTxt = String(txt || '').trim()

  // 1. Try parsing using embedded metadata token
  const metadataMatch = cleanTxt.match(/\[learnledger-test-data:([A-Za-z0-9+/=]+)\]/)
  if (metadataMatch?.[1]) {
    try {
      const jsonStr = decodeURIComponent(escape(atob(metadataMatch[1])))
      const parsed = JSON.parse(jsonStr)
      if (parsed && Array.isArray(parsed.questions)) {
        return parsed
      }
    } catch (err) {
      console.warn('Metadata parsing token failed, falling back to text parsing:', err)
    }
  }

  // 2. Fallback text parsing
  const lines = cleanTxt.split('\n').map((l) => l.trim())

  // Parse Title / Topic
  let topic = 'Imported Practice Test'
  const firstSepIdx = lines.indexOf(SEPARATOR)
  if (firstSepIdx !== -1 && lines[firstSepIdx + 1] && lines[firstSepIdx + 2] === SEPARATOR) {
    topic = lines[firstSepIdx + 1]
  }

  // Find QUESTIONS section
  const questionsStartIdx = lines.findIndex((l) => l === 'QUESTIONS')
  if (questionsStartIdx === -1) {
    throw new Error('Invalid test format: "QUESTIONS" section header not found.')
  }

  const questions = []
  const answers = {}
  let currentQuestion = null

  // Scan line by line starting from the QUESTIONS list
  for (let i = questionsStartIdx + 2; i < lines.length; i++) {
    const line = lines[i]

    if (line === SECTION_SEP || line.startsWith('[learnledger-test-data:')) {
      if (currentQuestion) {
        questions.push(currentQuestion)
        currentQuestion = null
      }
      continue
    }

    if (!line) continue

    // Detect Question start
    const qMatch = line.match(/^Q(\d+)\.\s*(.+)$/i)
    if (qMatch) {
      if (currentQuestion) {
        questions.push(currentQuestion)
      }
      currentQuestion = {
        id: `q_imported_${uid()}`,
        question: qMatch[2],
        options: [],
        correctAnswer: 'a',
        explanation: '',
        questionNumber: parseInt(qMatch[1], 10),
        difficulty: 'medium',
      }
      continue
    }

    // Detect Options (e.g. "A. option text")
    const optMatch = line.match(/^([A-D])\.\s*(.+)$/i)
    if (optMatch && currentQuestion) {
      currentQuestion.options.push({
        id: optMatch[1].toLowerCase(),
        text: optMatch[2]
      })
      continue
    }

    // Detect User Answer
    const userAnsMatch = line.match(/^Your Answer:\s*([A-D])/i)
    if (userAnsMatch && currentQuestion) {
      answers[currentQuestion.id] = userAnsMatch[1].toLowerCase()
      continue
    }

    // Detect Correct Answer
    const correctAnsMatch = line.match(/^Correct Answer:\s*([A-D])/i)
    if (correctAnsMatch && currentQuestion) {
      currentQuestion.correctAnswer = correctAnsMatch[1].toLowerCase()
      continue
    }

    // Detect Explanation
    if (line.startsWith('Explanation:')) {
      let explanationLines = []
      let j = i + 1
      while (j < lines.length && lines[j] !== SECTION_SEP && !lines[j].match(/^Q\d+\./) && !lines[j].startsWith('[learnledger-test-data:')) {
        explanationLines.push(lines[j])
        j++
      }
      if (currentQuestion) {
        currentQuestion.explanation = explanationLines.join('\n').trim()
      }
      i = j - 1
      continue
    }
  }

  if (currentQuestion) {
    questions.push(currentQuestion)
  }

  if (questions.length === 0) {
    throw new Error('Failed to parse any questions from the import file.')
  }

  // Calculate scores
  let correct = 0
  let incorrect = 0
  let unanswered = 0

  questions.forEach((q) => {
    const userAns = answers[q.id]
    if (!userAns) {
      unanswered++
    } else if (userAns === q.correctAnswer) {
      correct++
    } else {
      incorrect++
    }
  })

  const totalQuestions = questions.length
  const percentage = totalQuestions > 0 ? Math.round((correct / totalQuestions) * 100) : 0

  return {
    id: `imported-${Date.now()}-${uid()}`,
    topic,
    title: topic,
    createdAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
    questions,
    answers,
    score: correct,
    correct,
    incorrect,
    unanswered,
    totalQuestions,
    percentage,
    passed: percentage >= 70,
    status: 'completed'
  }
}

export function formatTestResultsOnlyAsTxt(test) {
  if (!test) return ''

  const title = safeStr(test.topic || test.title || test.name || 'Untitled Test').toUpperCase()
  const questions = Array.isArray(test.questions) ? test.questions : []
  const answers = test.answers && typeof test.answers === 'object' ? test.answers : {}
  const totalQuestions = questions.length

  let correct = 0
  let wrong = 0
  let skipped = 0

  questions.forEach((q) => {
    const userAnswer = answers[q.id]
    const correctAnswer = String(q.correctAnswer || '').toLowerCase()

    if (!userAnswer) {
      skipped++
    } else if (String(userAnswer).toLowerCase() === correctAnswer) {
      correct++
    } else {
      wrong++
    }
  })

  const scoreCorrect = test.score ?? test.correct ?? correct
  const scoreWrong = test.incorrect ?? wrong
  const scoreSkipped = test.unanswered ?? skipped
  const scorePercentage = test.percentage ?? (totalQuestions > 0 ? Math.round((scoreCorrect / totalQuestions) * 100) : 0)

  const lines = []

  lines.push(SEPARATOR)
  lines.push(title + ' - TEST RESULTS REVIEW')
  lines.push(SEPARATOR)
  lines.push('')
  lines.push(`Date: ${formatDate(test.completedAt || test.savedAt || test.createdAt)}`)
  lines.push(`Score: ${scoreCorrect} / ${totalQuestions}  (${scorePercentage}%)`)
  lines.push(`Correct: ${scoreCorrect}`)
  lines.push(`Wrong: ${scoreWrong}`)
  lines.push(`Skipped: ${scoreSkipped}`)
  lines.push('')

  const wrongQuestions = []
  const skippedQuestions = []

  questions.forEach((q, index) => {
    const questionNumber = index + 1
    const userAnswer = answers[q.id] || null
    const correctAnswer = String(q.correctAnswer || '').toLowerCase()
    const isCorrect = userAnswer && String(userAnswer).toLowerCase() === correctAnswer
    const isSkipped = !userAnswer

    if (isSkipped) {
      skippedQuestions.push({ q, questionNumber, correctAnswer })
    } else if (!isCorrect) {
      wrongQuestions.push({ q, questionNumber, userAnswer, correctAnswer })
    }
  })

  if (wrongQuestions.length > 0) {
    lines.push('WRONG ANSWERS')
    lines.push(SEPARATOR)
    wrongQuestions.forEach(({ q, questionNumber, userAnswer, correctAnswer }) => {
      lines.push('')
      lines.push(`Q${questionNumber}. ${safeStr(q.question || q.prompt || q.questionText)}`)
      lines.push(`Your Answer: ${optionLabel(userAnswer)}  —  ${getOptionText(q, userAnswer)}`)
      lines.push(`Correct Answer: ${optionLabel(correctAnswer)}  —  ${getOptionText(q, correctAnswer)}`)
      
      const explanation = safeStr(q.explanation)
      if (explanation) {
        lines.push('Explanation:')
        const cleanedExplanation = explanation
          .replace(/\\n/g, '\n')
          .replace(/\\t/g, '  ')
          .split('\n')
          .map((line) => `  ${line.trim()}`)
          .join('\n')
        lines.push(cleanedExplanation)
      }
      lines.push('')
      lines.push(SECTION_SEP)
    })
    lines.push('')
  }

  if (skippedQuestions.length > 0) {
    lines.push('MISSED/SKIPPED QUESTIONS')
    lines.push(SEPARATOR)
    skippedQuestions.forEach(({ q, questionNumber, correctAnswer }) => {
      lines.push('')
      lines.push(`Q${questionNumber}. ${safeStr(q.question || q.prompt || q.questionText)}`)
      lines.push(`Correct Answer: ${optionLabel(correctAnswer)}  —  ${getOptionText(q, correctAnswer)}`)
      
      const explanation = safeStr(q.explanation)
      if (explanation) {
        lines.push('Explanation:')
        const cleanedExplanation = explanation
          .replace(/\\n/g, '\n')
          .replace(/\\t/g, '  ')
          .split('\n')
          .map((line) => `  ${line.trim()}`)
          .join('\n')
        lines.push(cleanedExplanation)
      }
      lines.push('')
      lines.push(SECTION_SEP)
    })
    lines.push('')
  }

  lines.push('Generated by LearnLedger - Review mode')
  lines.push('')

  return lines.join('\n')
}

/**
 * Format only wrong and skipped questions for quick clipboard copy.
 *
 * @param {Object} test — Test object with questions, answers, etc.
 * @returns {string} — Formatted text string containing only mistakes & explanations
 */
export function formatWrongAnswersForClipboard(test) {
  if (!test) return ''

  const title = safeStr(test.topic || test.title || test.name || 'LearnLedger Test')
  const questions = Array.isArray(test.questions) ? test.questions : []
  const answers = test.answers && typeof test.answers === 'object' ? test.answers : {}
  const reviewExplanations = (
    test.reviewExplanations && typeof test.reviewExplanations === 'object'
      ? test.reviewExplanations
      : {}
  )

  const wrongOrSkipped = []

  questions.forEach((q, index) => {
    const questionNumber = q.questionNumber || index + 1
    const userAnswer = answers[q.id] || null
    const explanationItem = reviewExplanations[q.id] || null
    const correctAnswer = String(explanationItem?.correctAnswer || q.correctAnswer || '').trim().toLowerCase()

    const hasKey = ['a', 'b', 'c', 'd'].includes(correctAnswer)
    if (!hasKey) return

    const isCorrect = userAnswer && String(userAnswer).toLowerCase() === correctAnswer
    if (!isCorrect) {
      wrongOrSkipped.push({
        q,
        questionNumber,
        userAnswer,
        correctAnswer,
        isSkipped: !userAnswer,
        explanation: String(explanationItem?.explanation || q.explanation || '').trim()
      })
    }
  })

  if (wrongOrSkipped.length === 0) {
    return `🎉 Perfect Score! There are no wrong answers in "${title}". (Score: 100%)`
  }

  const lines = []
  lines.push(SEPARATOR)
  lines.push(`${title.toUpperCase()} — WRONG ANSWERS REVIEW`)
  lines.push(`Total Mistakes / Unattempted: ${wrongOrSkipped.length}`)
  lines.push(SEPARATOR)

  wrongOrSkipped.forEach((item, idx) => {
    const { q, questionNumber, userAnswer, correctAnswer, isSkipped, explanation } = item
    lines.push('')
    lines.push(`Q${questionNumber}. ${safeStr(q.question || q.prompt || q.questionText)}`)
    lines.push('')

    const options = Array.isArray(q.options) ? q.options : []
    if (options.length > 0) {
      options.forEach((opt) => {
        lines.push(`  ${optionLabel(opt.id)}. ${safeStr(opt.text)}`)
      })
      lines.push('')
    }

    if (isSkipped) {
      lines.push(`Your Answer: (Not Attempted / Skipped)`)
    } else {
      lines.push(`Your Answer: ${optionLabel(userAnswer)} — ${getOptionText(q, userAnswer)}`)
    }

    lines.push(`Correct Answer: ${optionLabel(correctAnswer)} — ${getOptionText(q, correctAnswer)}`)

    if (explanation) {
      lines.push('')
      lines.push('Explanation:')
      const cleanedExplanation = explanation
        .replace(/\\n/g, '\n')
        .replace(/\\t/g, '  ')
        .split('\n')
        .map((line) => `  ${line.trim()}`)
        .join('\n')
      lines.push(cleanedExplanation)
    }

    if (idx < wrongOrSkipped.length - 1) {
      lines.push('')
      lines.push(SECTION_SEP)
    }
  })

  lines.push('')
  lines.push(SEPARATOR)
  return lines.join('\n')
}

